github: [ 'NotAKidOnSteam', 'SupinePandora43' ]
custom: [ 'https://steamcommunity.com/profiles/76561198100664745', 'http://steamcommunity.com/tradeoffer/new/?partner=466321232&token=CVmPnEke' ] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
