name: Lint
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest # ubuntu is fastest
    steps:
    - uses: actions/checkout@v1
    - name: Download glualint
      run: |
        wget https://github.com/FPtje/GLuaFixer/releases/download/1.11.2/glualint-1.11.2-linux.zip
        unzip glualint-1.11.2-linux.zip
    - name: Lint
      run: ./glualint .
